spring.application.name=CompactURL
 
# PostgreSQL connection settings

spring.datasource.url=jdbc:postgresql://postgres:5432/c_url
spring.datasource.username=postgres
spring.datasource.password=postgres@1
 
# Hibernate / JPA settings

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.orm.connections.pooling=WARN
 
# Redis Configuration

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=60000
 
# Base URL

app.base-url=http://localhost:8080/